version: '3.8'

services:
  backend:
    build:
      context: ./report-engine
      dockerfile: Dockerfile
    container_name: report-engine
    ports:
      - "8000:8000"
    volumes:
      - ./workspace_data:/workspace
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./Intellicheck-AI
      dockerfile: Dockerfile
    container_name: intellicheck-ai
    ports:
      - "5173:80"
    depends_on:
      - backend
